{
 "title": "Intel GPU",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU load1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    { "expr": "system_load1", "legendFormat": "{{__name__}}" }
   ]
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Frequency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "rotmhz" } },
   "targets": [
    {
     "expr": "intel_gpu_top_frequency_requested",
     "legendFormat": "requested [{{unit}}]"
    },
    { "expr": "intel_gpu_top_frequency_actual", "legendFormat": "actual [{{unit}}]" }
   ]
  },
  {
   "title": "Interrupts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 18 },
   "targets": [
    { "expr": "intel_gpu_top_interrupts", "legendFormat": "{{unit}}" }
   ]
  },
  {
   "title": "RC6",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "intel_gpu_top_rc6", "legendFormat": "{{unit}}" }
   ]
  },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "intel_gpu_top_power_gpu", "legendFormat": "GPU [{{unit}}]" },
    { "expr": "intel_gpu_top_power_package", "legendFormat": "Package [{{unit}}]" }
   ]
  },
  {
   "title": "IMC Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "expr": "intel_gpu_top_imc_bandwidth_reads",
     "legendFormat": "reads [{{unit}}]"
    },
    {
     "expr": "intel_gpu_top_imc_bandwidth_writes",
     "legendFormat": "writes [{{unit}}]"
    }
   ]
  },
  { "title": "Engines", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Render3d",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max(intel_gpu_top_engines_render3d_busy)",
     "legendFormat": "busy [{{unit}}]"
    },
    {
     "expr": "max(intel_gpu_top_engines_render3d_sema)",
     "legendFormat": "sema [{{unit}}]"
    },
    {
     "expr": "max(intel_gpu_top_engines_render3d_wait)",
     "legendFormat": "wait [{{label_name}}]"
    }
   ]
  },
  {
   "title": "Blitter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max(intel_gpu_top_engines_blitter_busy)",
     "legendFormat": "busy [{{unit}}]"
    },
    {
     "expr": "max(intel_gpu_top_engines_blitter_sema)",
     "legendFormat": "sema [{{unit}}]"
    },
    {
     "expr": "max(intel_gpu_top_engines_blitter_wait)",
     "legendFormat": "wait [{{label_name}}]"
    }
   ]
  },
  {
   "title": "Video",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max(intel_gpu_top_engines_video_busy)",
     "legendFormat": "busy [{{unit}}]"
    },
    {
     "expr": "max(intel_gpu_top_engines_video_sema)",
     "legendFormat": "sema [{{unit}}]"
    },
    {
     "expr": "max(intel_gpu_top_engines_video_wait)",
     "legendFormat": "wait [{{label_name}}]"
    }
   ]
  },
  {
   "title": "VideoEnhance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max(intel_gpu_top_engines_video_enhance_busy)",
     "legendFormat": "busy [{{unit}}]"
    },
    {
     "expr": "max(intel_gpu_top_engines_video_enhance_sema)",
     "legendFormat": "sema [{{unit}}]"
    },
    {
     "expr": "max(intel_gpu_top_engines_video_enhance_wait)",
     "legendFormat": "wait [{{label_name}}]"
    }
   ]
  },
  { "title": "Exporter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Data delay",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - intel_gpu_top_updated_at",
     "legendFormat": "{{unit}}"
    }
   ]
  },
  {
   "title": "Refresh period",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(intel_gpu_top_period[5m])",
     "legendFormat": "{{unit}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 77 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "intel_gpu_top_errors", "legendFormat": "{{__name__}}" }
   ]
  }
 ]
}